---
- name: Update and upgrade apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
 
- name: "Install Nginx"
  apt:
    name: nginx
    update_cache: yes
    state: latest
 
- name: Copy the Nginx configuration file to the host
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Create link to the new config to enable it
  file:
    dest: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link
 
- name: Create Nginx directory
  file:
    path: "{{ nginx_custom_directory }}"
    state: directory
 
- name: Copy icon.png to the Nginx directory
  copy:
    src: files/icon.png
    dest: "{{ nginx_custom_directory }}"

- name: Copy robots.txt to the Nginx directory
  copy:
    src: files/robots.txt
    dest: "{{ nginx_custom_directory }}"

- name: Copy assets to the Nginx directory
  copy:
    src: files/assets/
    dest: "{{ nginx_custom_directory }}/assets/"

- name: Copy index.html to the Nginx directory
  copy:
    src: files/index.html
    dest: "{{ nginx_custom_directory }}/index.html"
  notify: Restart the Nginx service
